configuration: Release
version: 2.0.0-beta{build}
image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
- cmd: nuget install nuget.commandline -source https://dotnet.myget.org/F/nuget-build -prerelease -excludeversion
- cmd: set PATH=%appveyor_build_folder%\NuGet.CommandLine\tools;%PATH%
- cmd: dotnet.exe restore

after_build:
- ps: >-
    $versionSuffix=(Get-Item Env:APPVEYOR_BUILD_NUMBER).Value
    
    Set-Location "nupkg"
    
    .\pack.ps1 -versionSuffix "$versionSuffix"

build:
  verbosity: minimal

pull_requests:  
  do_not_increment_build_number: true

test:
  assemblies:
  - test\StudioX.Zero.SampleApp.Tests\bin\Release\net452\StudioX.Zero.SampleApp.Tests.dll
 # - test\StudioX.Zero.SampleApp.EntityFrameworkCore.Tests\bin\Release\net461\StudioX.Zero.SampleApp.EntityFrameworkCore.Tests.dll
  
artifacts:
- path: nupkg\*.nupkg
  name: nuget-packages